# Funding Configuration
# Descomente e configure as plataformas que você usa

# GitHub Sponsors
# github: [seu-usuario]

# Patreon
# patreon: seu-usuario

# Open Collective
# open_collective: lumina-engine

# Ko-fi
# ko_fi: seu-usuario

# Buy Me a Coffee
# custom: https://www.buymeacoffee.com/seu-usuario

# PayPal
# custom: https://www.paypal.me/seu-usuario

# PIX (Brasil)
# custom: ['https://nubank.com.br/pagar/seu-link']
